default_platform :ios

platform :ios do

  desc "Runs all the tests (debug and release)"
  lane :test do
    test_debug
    test_release
  end

  desc "Run Debug tests"
  lane :test_debug do
    scan(configuration: "Debug")
  end

  desc "Run Release tests"
  lane :test_release do
    scan(configuration: "Release")
  end

  after_all do |lane|
    if lane.equal? :test
      puts "🌯 🌯 🌯  Burrito Time! 🌯 🌯 🌯"
    end
  end

  error do |lane, exception|
    puts "Not burrito time..."
  end

end
