default_platform :ios

platform :ios do

  desc "Runs all the tests (debug and release) and generates code coverage files"
  lane :test do
    test_debug
    test_release
    code_coverage
  end

  desc "Run Debug tests"
  lane :test_debug do
    scan(configuration: "Debug")
  end

  desc "Run Release tests"
  lane :test_release do
    scan(configuration: "Release")
  end

  desc "Get Code Coverage"
  lane :code_coverage do
    scan(
      xcargs: "OBJROOT=build GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES"
    )
  end

  after_all do |lane|
    if lane.equal? :test
      puts "🌯 🌯 🌯  Burrito Time! 🌯 🌯 🌯"
    end
  end

  error do |lane, exception|
    puts "Not burrito time..."
  end

end
